---
title: "Deforestation detection using SITS"
output: rmarkdown::html_vignette
bibliography: references.bib
vignette: >
  %\VignetteIndexEntry{datacube}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo = FALSE}
# devtools::install_github("albhasan/sits.starfm")
suppressMessages(library(sits.prodes))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(tidyr))
suppressMessages(library(purrr))
library(rnaturalearth)
library(rnaturalearthdata)

data("BRICK_IMAGES", package = "sits.starfm")
```

## Introduction

* SITS - satellite image time series - an R package

## Study area

```{r maps, echo=FALSE, fig.width=7, fig.height=4}


# TODO: debug BRICK_IMAGES


# BRICK_IMAGES %>%
#     dplyr::select(sat_image, scene, files) %>%
#     tidyr::unnest() %>%
#     dplyr::mutate(
#         scene_sat_image = purrr::map_chr(.$sat_image, function(x){unlist(stringr::str_split(x, "_"))[3]}),
#         scene_file =      purrr::map_chr(.$file_path, function(x){unlist(stringr::str_split(basename(x), "_"))[3]})
#     ) %>%
#     dplyr::mutate(test_res = all.equal(scene, scene_sat_image, scene_file)) %>%
#     ensurer::ensure_that(all(.$test_res), err_desc = "Scene missmatch")
# 
# BRICK_IMAGES$cat_extent <- lapply(BRICK_IMAGES$img_extent, function(x){paste0(x, collapse = "_")})
# BRICK_IMAGES %>%
#     dplyr::pull(cat_extent) %>%
#     unique()
    
    





img_extent <- BRICK_IMAGES %>% dplyr::select(scene, img_extent) %>% 
    dplyr::group_by(scene) %>% 
    dplyr::slice(dplyr::n()) %>% 
    dplyr::ungroup() %>% 
    dplyr::pull(img_extent)
map_bz <- ggplot2::ggplot(data = rnaturalearth::ne_countries(scale = "small", 
                                                             returnclass = "sf")) +
    ggplot2::geom_sf() +
    ggplot2::coord_sf(xlim = c(-74, -34), ylim = c(-34, 6), expand = FALSE)
for (i_ext in img_extent) {
    map_bz <- map_bz + ggplot2::geom_rect(xmin = i_ext["xmin"], 
                                          xmax = i_ext["xmax"], 
                                          ymin = i_ext["ymin"], 
                                          ymax = i_ext["ymax"], 
                                          fill = NA, colour = "black", size = 1.0)
}
print(map_bz)

```




## Data


```{r brick_desc, echo=FALSE}
brick_description %>% 
    knitr::kable(digits = 2, row.names = TRUE, full_width = FALSE) %>% 
    kableExtra::kable_styling()
```



```{r cloud_cover, echo=FALSE, fig.width=7, fig.height=4}
cloud_cover <- BRICK_IMAGES %>% 
    dplyr::select(scene, img_date, cloud_cov, prodes_year) %>% 
    dplyr::mutate(doy = lubridate::yday(img_date),
                  prodes_doy = ifelse(doy > 214, doy - 214, doy)) %>% 
    dplyr::arrange(scene, prodes_year, prodes_doy) %>% 
    ggplot2::ggplot(ggplot2::aes(x = prodes_doy, y = cloud_cov)) + 
        ggplot2::ylim(0, 1) +
        ggplot2::geom_line() +
        ggplot2::facet_grid(prodes_year ~ scene) +
        ggplot2::geom_smooth(se = FALSE, method = 'loess', formula = 'y ~ x')

suppressWarnings(print(cloud_cover))
```


### Imagery

### Samples

## Methods

## Results and discussion

## PRODES vs. Mapbiomas
